### ISSUE TITLE
Theme not updated in correct directory as specifiied by `book.toml`

### ISSUE THREAD

**Issue by stevenj** [zjp-CN/mdbook-theme#6]
https://github.com/zjp-CN/mdbook-theme/commit/df01754a32f259a9f001ea653c8e9de67c59c0b9 broke theme updates for me.

The theme now always seems to get installed into the project root `./theme` directory.
My theme directory is actually in `book/assets/theme`
And is properly declared in the `book.toml` as:
```toml
[output.html]
theme          = "book/assets/theme"
```
