### ISSUE TITLE
Bug: options like `content-main-margin-left` brings nothing

### ISSUE THREAD

**Issue by zjp-CN** [zjp-CN/mdbook-theme#8]
```toml
[preprocessor.theme]
content-main-margin-left = "4%"
content-main-margin-right = "15%"
```

results in nothing changed.

This is because we don't parse css. We search for strings and replace the specified options. 

So currently there must be the properties in css:

```css
/* theme/css/general.css */
.content main {
    margin-inline-start: auto;
    margin-inline-end: auto;
    max-width: var(--content-max-width);
    /* the following properties may be missing, so you have to add them*/
    margin-left: 5%;
    margin-right: 15%;
}
```
